---
# ConfigMap for api-gateway
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  PORT: "5000"
  AUTH_SERVICE_URL: "http://auth-service:5001"
---
# ConfigMap for auth-service
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  PORT: "5001"
  DBSTRING: "postgresql://postgres:postgres123@47.128.225.20:5432/postgres?sslmode=disable"
  JWT_SECRET: "DeadLock"
  JWT_EXPIRES_IN: "360000"
---
# ConfigMap for inventory-service
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
data:
  PORT: "5002"
  DBSTRING: "postgresql://postgres:postgres123@47.128.225.20:5432"
  CORS_ALLOWED_ORIGIN: "*"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
  LOG_STYLE: "json"
  LOG_LEVEL: "debug"
