---
# ConfigMap for api-gateway
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  PORT: "5000"
  AUTH_SERVICE_URL: "http://auth-service:5001"
---
# ConfigMap for auth-service
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  PORT: "5001"
  POSTGRES_URI: "postgresql://postgres:postgres123@47.128.225.20:5432/postgres?sslmode=disable"
  JWT_SECRET: "DeadLock"
  JWT_EXPIRES_IN: "360000"
